# ===============================
# LIBRERÍAS REQUERIDAS
# ===============================
library(shiny)
library(shinydashboard)
library(tidyverse)
library(tidyquant)
library(quantmod)
library(PerformanceAnalytics)
library(PortfolioAnalytics)
library(ROI)
library(ROI.plugin.glpk)
library(plotly)
library(DT)
library(xts)
library(heatmaply)
library(corrplot)
library(viridisLite)
library(zoo)
library(timetk)
library(caret)
library(xgboost)
library(htmltools)
library(yardstick)
library(moments)
library(dlm)
library(quadprog)

# ===============================
# SOURCE DE FUNCIONES (carpeta R/)
# ===============================
source("../R/data_utils.R")
source("../R/indicators.R")
source("../R/portfolio_analysis.R")
source("../R/ml.R")
source("../R/pairs.R")
source("../R/monte_carlo.R")
source("../R/black_litterman.R")
source("../R/performance_metrics.R")
